import '../button/style'
import '../tag/style'
import '../tabs/style'
import '../layout/style'
import '../progress/style'
import '../loading/style'
import '../back-top/style'
import '../card/style'
import './response.scss'

