name: Bundle Size

on: [pull_request]

jobs:
  build:
    name: Check compressed size
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: '${{ secrets.GH_TOKEN }}'
