# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js latest

on:
  push:
    tags-ignore:
      - v*.*.*-alpha.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Execute lint
        run: pnpm run lint

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
          registry-url: 'https://npm.zzfzzf.com/'
          always-auth: true
          scope: '@zzf'

      - name: Install dependencies
        run: pnpm --filter @zzf/design run build

      - name: Build
        run: pnpm --filter @zzf/design run build

      - run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
